name: Jm
favicon: null
layout_spectrum: 0.23942
typography_spectrum: 0.48679
title: 'Thoughts from a Vagabond Entrepreneur '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-39245915-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7688ac'
    - '#ede8e4'
    - '#47505f'
    - '#3e3629'
    - '#9aa9c6'
  brandStrength: 0.08125938987359405
  lightness: 0.7532875521574169
  saturation: 0.7197855182457715
  rhythmicContrast: 0.6099740453064442
purpose: []
